package schemagen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseFlattensExportedWireShape(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "types.go")
	source := `package fixture

// Details documents the embedded fields.
type Details struct {
	// Count is required.
	Count int ` + "`json:\"count\" toml:\"item_count\"`" + `
	hidden string
	Ignored string ` + "`json:\"-\"`" + `
	*Cycle
}

type Cycle struct { *Details }

// Zebra documents the outer type.
type Zebra struct {
	Details
	// Label is optional.
	Label string ` + "`json:\"label,omitempty\"`" + `
}

type Alpha struct { Value []string }
type alias string
type hidden struct { Public string }
`
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}

	prims, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(prims) != 4 {
		t.Fatalf("Parse returned %d primitives: %+v", len(prims), prims)
	}
	if prims[0].Name != "Alpha" || prims[1].Name != "Cycle" || prims[2].Name != "Details" || prims[3].Name != "Zebra" {
		t.Fatalf("primitive order = %+v", prims)
	}
	zebra := prims[3]
	if zebra.Doc != "Zebra documents the outer type." || len(zebra.Fields) != 2 {
		t.Fatalf("Zebra = %+v", zebra)
	}
	count := zebra.Fields[0]
	if count.Name != "Count" || count.Type != "int" || count.JSONName != "count" || count.TOMLName != "item_count" || !count.Required || count.Doc != "Count is required." {
		t.Fatalf("flattened Count = %+v", count)
	}
	label := zebra.Fields[1]
	if label.Name != "Label" || label.JSONName != "label" || label.TOMLName != "label" || label.Required || label.Doc != "Label is optional." {
		t.Fatalf("Label = %+v", label)
	}
	if got := prims[0].Fields[0]; got.Type != "[]string" || got.JSONName != "Value" || got.TOMLName != "Value" || !got.Required {
		t.Fatalf("Alpha.Value = %+v", got)
	}
}

func TestGenerateAndRenderProduceFormattedSource(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "types.go")
	if err := os.WriteFile(path, []byte("package fixture\n// Item docs.\ntype Item struct { Name string `json:\"name\" toml:\"item_name\"` }\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := Generate(path)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	text := string(got)
	for _, want := range []string{
		"// Code generated by internal/formula/cmd/schemagen. DO NOT EDIT.",
		"package formula",
		`Name: "Item"`,
		"Doc:  `Item docs.`",
		`JSONName: "name"`,
		`TOMLName: "item_name"`,
		"Required: true",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("generated source missing %q:\n%s", want, text)
		}
	}

	quoted, err := Render([]Primitive{{Name: "Quoted", Doc: "contains `tick`", Fields: []Field{{Name: "Control", Type: "string", JSONName: "control", Doc: "line\u0001"}}}})
	if err != nil {
		t.Fatalf("Render quoted strings: %v", err)
	}
	if !strings.Contains(string(quoted), "\"contains `tick`\"") || !strings.Contains(string(quoted), `"line\x01"`) {
		t.Fatalf("Render did not quote unsafe raw strings:\n%s", quoted)
	}
}

func TestParseReportsSourceError(t *testing.T) {
	path := filepath.Join(t.TempDir(), "broken.go")
	if err := os.WriteFile(path, []byte("package broken\ntype"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := Parse(path); err == nil || !strings.Contains(err.Error(), "parse "+path) {
		t.Fatalf("Parse(broken) error = %v", err)
	}
}

func TestStructTagParsingBoundaries(t *testing.T) {
	tag := newReflectStructTag(`json:"name,omitempty" toml:"item_name"`)
	if got, ok := tag.lookup("json"); !ok || got != "name,omitempty" {
		t.Fatalf("json lookup = (%q, %v)", got, ok)
	}
	if got, ok := tag.lookup("toml"); !ok || got != "item_name" {
		t.Fatalf("toml lookup = (%q, %v)", got, ok)
	}
	if _, ok := tag.lookup("yaml"); ok {
		t.Fatal("missing tag reported present")
	}
	for _, malformed := range []reflectStructTag{`broken`, `json:`, `json:"unterminated`} {
		if _, ok := malformed.lookup("json"); ok {
			t.Errorf("malformed tag %q reported present", malformed)
		}
	}
}
