package main

type VersionChange struct {
	Version string   `json:"version"`
	Date    string   `json:"date"`
	Changes []string `json:"changes"`
}

// versionChanges contains agent-actionable changes for recent versions
var versionChanges = append(append([]VersionChange{}, versionChangesRecent...), versionChangesOlder...)

var versionChangesRecent = []VersionChange{
	{
		Version: "1.2.3",
		Date:    "2026-08-26",
		Changes: []string{
			"FIX: issue titles reject invalid UTF-8 and report the 500-byte limit as bytes, not characters — a 167-rune CJK title is no longer described as 501 characters, and JSONL export can no longer silently replace a corrupt title with U+FFFD (#15).",
			"FIX: query lexer decodes full UTF-8 runes instead of casting each byte to a rune, so predicates like label=\"café\" match real Unicode field data (#14).",
		},
	},
	{
		Version: "1.2.2",
		Date:    "2026-08-20",
		Changes: []string{
			"FIX: dbproxy self-heal no longer misses a dead backend when DatabaseServer.Running() lags the OS-level Dial() failure by the process-reap window; a bounded re-poll (backendConfirmedDead) closes the race so the proxy always self-heals instead of hanging forever against a dead backend (#12).",
		},
	},
	{
		Version: "1.2.1",
		Date:    "2026-08-11",
		Changes: []string{
			"MIGRATION: first open with this binary runs migration 0062 (events -> dolt_ignored storage, bd-red8u): a one-time four-phase self-committing flip that removes per-event dolt commit churn. Expect one slower first invocation per clone; do not interrupt it.",
			"NEW: `bd sync` — the federation loop (export, commit, pull, import, push) as one verb.",
			"NEW: `--brief` on `bd list` / `bd ready --json` and the HTTP listings — omits free-form text fields (~93% smaller payloads on large stores); fields are omitted without a marker, so only the caller that passed the flag knows rows are partial.",
			"BEHAVIOR: expired dated defers now AUTO-WAKE on ready-front reads and claims (#5386) — a lapsed `--defer` no longer hides an issue forever; stale defers surface on the next `bd ready`.",
			"PERF: telemetry no longer costs startup time on every invocation (#5646), and the queued-events dir is bounded (7d TTL + drop-oldest caps, #5660) — a backlogged ~/.beads/eventsData self-prunes.",
		},
	},
	{
		Version: "1.1.2",
		Date:    "2026-07-26",
		Changes: []string{
			"FIX: the v53 aux row re-key no longer aborts the migration on dolt#11131 encoding drift ('invalid hash length' panic); drifted tables are skipped with a warning, recorded clone-locally, and retried on later passes instead of leaving the database unopenable (#4380).",
		},
	},
	{
		Version: "1.1.0",
		Date:    "2026-07-04",
		Changes: []string{
			"STABLE: first stable 1.1.x release; includes the rc.1 and rc.2 cross-clone migration-safety work plus post-rc.2 recovery fixes.",
			"UPGRADE: back up with bd export --all before migrating older or remote-backed databases; the upgrade docs now carry the stable 1.1.0 recipes.",
			"FIX: failed v53 migrations can self-heal on the next open, including wisp_dependencies split-column drift and dirty snapshot tables left by a half-applied pass (#4555, #4558).",
			"FIX: bd dolt commit and bd vc commit can commit a dirty embedded working set that is blocking a pending schema migration; after that, bd migrate can proceed (#4566, #4567).",
			"NEW: the state-aware remote-migrate gate is enabled by default; safe first-mover migrations proceed, while remote-ahead or content-skew cases still stop for adoption or human review (#4516).",
		},
	},
	{
		Version: "1.1.0-rc.2",
		Date:    "2026-07-02",
		Changes: []string{
			"RC: fixes the two upgrade-breaking migration regressions reported against rc.1 (#4502, #4534); back up with bd export --all before migrating a remote-backed database.",
			"FIX: the v53 migration no longer fails with Unknown column on databases whose issues table predates the rig/agent columns; the runner repairs the drift before applying (#4502).",
			"FIX: an orphaned child_counters row no longer bricks every bd create after the fk_counter_parent constraint returned; a clone-local cleanup migration heals affected databases automatically (#4534).",
			"FIX: old binaries fail fast on writable opens of a schema-newer database instead of proceeding blind (#4531).",
			"NEW: the remote-migrate gate is state-aware and agent-safe — provably safe migrations auto-resolve; risky states still require BD_ALLOW_REMOTE_MIGRATE=1 by the designated migrator (#4515, #4516).",
			"UPGRADE: the upgrade guide now carries a validated remote-backed / multi-clone recipe with a pre-migrate backup step (#4514).",
		},
	},
	{
		Version: "1.1.0-rc.1",
		Date:    "2026-06-23",
		Changes: []string{
			"RC: v1.0.5 was pulled from the default release path after #4259; this candidate carries the cross-clone data-safety fixes for validation before stable promotion.",
			"UPGRADE: For multiple clones sharing one Dolt remote, sync every clone before upgrading, designate one machine to migrate and push, then upgrade/pull the remaining clones before doing tracked work.",
			"NEW: bd refuses silent in-place schema migrations on existing remote-backed databases unless BD_ALLOW_REMOTE_MIGRATE=1 is set by the designated migrator.",
			"NEW: schema_migrations records per-migration content hashes, and bd doctor reports migration-content skew against the cached remote-tracking ref.",
			"FIX: dependencies and wisp_dependencies now use deterministic natural-key-derived IDs, with migration 0050 rekeying existing rows and same-edge pull conflicts auto-resolved when only audit columns differ.",
			"FIX: Dolt primary-key merge refusals are classified with recovery guidance instead of surfacing only a raw Error 1105.",
		},
	},
	{
		Version: "1.0.5",
		Date:    "2026-05-28",
		Changes: []string{
			"CHANGE: dependencies.depends_on_id is now a STORED generated column — writes must target exactly one of depends_on_issue_id/depends_on_wisp_id/depends_on_external (enforced by ck_dep_one_target); inserting into depends_on_id fails. Migrations 0041–0042 are intentionally irreversible (restore from a prior Dolt commit to roll back).",
			"CHANGE: JSONL auto-export and auto-staging are now opt-in — set export.auto=true and export.git-add=true to keep the old behavior. Dolt is the canonical store; use bd dolt push/pull for sync and bd backup for restorable backups.",
			"CHANGE: Foreign keys with ON DELETE/UPDATE CASCADE now span issue and wisp tables, so parent delete/rename cascades automatically.",
			"NEW: dolt.mode config key (server|embedded) with validation; bd init warns on ambiguous configs and hard-fails when dolt.host/dolt.port are set without server mode.",
			"NEW: forward schema-skew guard hard-fails when a binary opens a database migrated to a newer schema than it understands.",
			"NEW: bd list --skip-labels toggle; bd show --json count-only details with opt-in streamed payloads.",
			"FIX: bd close supports per-id reasons and idempotent re-close; bd create --defer <future> creates a deferred issue; bd create commits labels atomically.",
			"FIX: migrations run on a connection with no read timeout; duplicate migration version numbers hard-fail instead of silently under-applying.",
		},
	},
	{
		Version: "1.0.4",
		Date:    "2026-05-07",
		Changes: []string{
			"NEW: bd init-safety plus --reinit-local/--discard-remote make remote-history destructive init paths explicit, with stable refusal exit codes 10/11/12",
			"CHANGE: bd init --force is now local-only and deprecated in favor of --reinit-local; use --discard-remote only when intentionally replacing remote Dolt history",
			"CHANGE: beads.OpenBestAvailable now returns (Storage, error); SDK callers must drop the removed Unlocker return value",
			"FIX: bd close now uses routed ID resolution in contributor auto-routing workspaces, matching show/update behavior",
			"FIX: Dolt-in-git internal refs/dolt/data pushes skip git hooks to avoid hook recursion",
			"FIX: release workflow and packaging paths hardened for the v1.0.4 release attempt, including checked-in formula adoption and pure-Go test helper coverage",
		},
	},
	{
		Version: "1.0.3",
		Date:    "2026-04-24",
		Changes: []string{
			"FIX: go install @latest — new release tag removes the go.mod replace directives that made v1.0.1 and v1.0.2 uninstallable via go install",
			"FIX: npm macOS installs — release archives are flat so npm postinstall finds the bd binary at the archive root",
			"FIX: Windows install — make install removes stale extensionless bd before installing bd.exe so old binaries do not shadow the new executable",
			"FIX: Windows test portability and embedded pre-commit export cwd handling",
		},
	},
	{
		Version: "1.0.2",
		Date:    "2026-04-15",
		Changes: []string{
			"FIX: npm publish — updated npm-package/package.json URLs (repository, bugs, homepage) from steveyegge/beads to gastownhall/beads so sigstore provenance validation accepts the artifact (v1.0.0 and v1.0.1 npm publishes failed E422 on provenance verification)",
		},
	},
	{
		Version: "1.0.1",
		Date:    "2026-04-15",
		Changes: []string{
			"NEW: bd batch — atomic multi-operation transactions across create/update/close/dep",
			"NEW: bd config drift / bd config apply — detect and reconcile config drift across yaml, git, and database",
			"NEW: bd config show — unified provenance view for effective config values",
			"NEW: started_at timestamp on issues (recorded when first entering in_progress)",
			"NEW: Selective sync — --issues flag, push/pull subcommands, --parent port across trackers",
			"NEW: Pool metrics telemetry for shared-server connection pool diagnosis",
			"NEW: OpenBestAvailable public API for library consumers",
			"NEW: az:// (Azure Blob Storage) recognized as Dolt remote URL scheme",
			"NEW: BEADS_DOLT_READY_TIMEOUT env var to override 10s waitForReady timeout on slow hardware",
			"CHANGE: Auto-export enabled by default — export.path defaults to issues.jsonl, git-add on",
			"CHANGE: gms_pure_go by default — ICU linkage dropped from test/install helpers and release binaries",
			"FIX: Worktree-aware path resolution across hooks, doctor, config validate, bootstrap, reset, rename-prefix, formula search",
			"FIX: Schema migration conflict and wisp-tables-missing-after-bootstrap-clone",
			"FIX: bd mol bond now detects transitive dependency cycles",
			"FIX: bd dep add/remove allows cross-prefix dependency targets",
			"FIX: bd dolt pull nil-pointer panic in embedded mode",
			"FIX: bd list truncation hint shown in all output modes; --watch hierarchy ordering stable",
			"FIX: bd update --defer correctly sets status=deferred",
			"FIX: Remote URL validation hardened at config parse time (security)",
			"FIX: GitLab issue link dependencies now imported during sync pull",
			"FIX: SQLite-era JSONL migration preserves dependencies and labels",
			"FIX: MCP workspace discovery detects Dolt-backed projects",
			"FIX: go install on Windows (ICU header dependency removed)",
		},
	},
	{
		Version: "0.63.3",
		Date:    "2026-03-29",
		Changes: []string{
			"NEW: Embedded Dolt is now the default storage backend — no separate server needed",
			"NEW: bd create --graph for batch issue creation from dependency graphs",
			"NEW: Multi-project/team sync for Linear, Jira, and ADO",
			"NEW: Notion sync reimplemented on REST data sources",
			"NEW: GitLab group-level issue sync",
			"NEW: Top-level command aliases (comment, assign, tag, link, priority)",
			"NEW: Storage API expansion — ListWisps, MergeSlot, ReopenIssue, and more",
			"CHANGE: Backup system simplified — git-based backup removed, Dolt-native only",
			"CHANGE: Dolt writeRetryTx auto-retries on serialization errors",
			"FIX: Init git cache reset prevents stale embedded refs",
			"FIX: CWD .beads/ priority over git-worktree resolution",
			"FIX: Epic closure correctly includes wisp children",
			"FIX: Prefix routing for edit, reopen, and delete commands",
			"FIX: ADO/Jira custom type_map no longer silently ignored",
		},
	},
	{
		Version: "0.62.0",
		Date:    "2026-03-21",
		Changes: []string{
			"NEW: Custom status categories (active/wip/done/frozen) control bd ready and bd list behavior",
			"NEW: bd statuses command lists all statuses with icons and categories",
			"NEW: bd note command for quick note appending",
			"NEW: Audit logging of status changes to interactions.jsonl",
			"NEW: --exclude-type flag for bd ready and bd list",
			"NEW: Azure DevOps integration (bd ado sync/status/projects)",
			"NEW: Memories included in export/import round-trip",
			"CHANGE: BEADS_ACTOR replaces BD_ACTOR as primary env var",
			"CHANGE: ServerMode enum consolidates Dolt server ownership inference",
			"CHANGE: Internal GT-specific concepts removed — beads is now standalone",
			"FIX: Windows Dolt lifecycle — stale state files, false stop warnings",
			"FIX: Hook preservation — all hooks preserved on core.hooksPath override",
			"FIX: Shim timeout 30s→300s — chained hooks no longer killed prematurely",
			"FIX: GetNextChildIDTx broken SQL CAST for non-numeric IDs",
			"FIX: Credential key added to project-root .gitignore",
			"FIX: Concurrent initSchemaOnDB serialized with GET_LOCK",
			"FIX: External Dolt servers no longer killed by KillStaleServers",
		},
	},
	{
		Version: "0.61.0",
		Date:    "2026-03-15",
		Changes: []string{
			"NEW: --no-history flag separates Dolt commit skipping from GC eligibility",
			"NEW: --claim-next on close auto-claims next ready issue",
			"NEW: Auto-detect beads database on git origin during init/bootstrap",
			"NEW: Install checksum verification (SHA256)",
			"NEW: --exclude-type for wisp GC, --type filter for wisp list",
			"NEW: Jira pull_jql config for custom JQL filters",
			"CHANGE: Prime SSOT — versioned hash-based markers, profile support, staleness detection",
			"CHANGE: Formula extends merges child steps by ID instead of appending",
			"CHANGE: Circuit breaker keyed on host:port, not port only",
			"CHANGE: Backup export/restore scoped by project prefix",
			"FIX: Embedded Dolt CI — stale noms LOCK cleanup, test fixes",
			"FIX: Port-0 circuit breaker poisoning prevention",
			"FIX: KillStaleServers scoped to repo, port resolution chain fix",
			"FIX: Doctor fingerprint, auto-start, runtime detection fixes",
			"FIX: Credential key moved to .beads/ (no ghost directories)",
			"FIX: UUID primary keys for federation-safe events/comments",
		},
	},
	{
		Version: "0.60.0",
		Date:    "2026-03-12",
		Changes: []string{
			"NEW: bd bootstrap executes recovery actions directly (hands-free repair)",
			"NEW: bd context command for safe-first error guidance",
			"NEW: bd help --list and --doc for CLI doc generation",
			"NEW: bd done alias for bd close; bd done <id> <message> for inline close reason",
			"NEW: --design-file flag for reading design from files",
			"NEW: --destroy-token for safe non-interactive re-init (GH#2497)",
			"NEW: GitHub Issues tracker plugin integration (GH#2373)",
			"NEW: Global ~/.config/beads/PRIME.md fallback (GH#2330)",
			"NEW: Shared Dolt server mode for multi-repo/agent setups (GH#2416)",
			"NEW: Ephemeral port allocation replaces hash-derived Dolt ports (GH#2415)",
			"NEW: Epic close guards with merge re-parenting and progress display",
			"NEW: bd search searches external_ref field (GH#2494)",
			"NEW: JSON-aware error output with JSONL schema validation (GH#2499)",
			"NEW: ai.api_key config fallback for ANTHROPIC_API_KEY",
			"CHANGED: Dolt ports are now OS-assigned ephemeral (no more collisions)",
			"CHANGED: Auto-push state moved to local file (prevents metadata merge conflicts)",
			"CHANGED: Charm glamour v2 and huh v2 upgrades",
			"CHANGED: Final daemon and idle monitor infrastructure removal",
			"FIX: Dolt journal corruption — KillStaleServers inside flock (GH#2430)",
			"FIX: Dolt config corruption from stale working set (GH#2455)",
			"FIX: Auto-commit before pull prevents merge errors (GH#2474)",
			"FIX: DOLT_PULL wrapped in explicit transaction (GH#2501)",
			"FIX: bd dolt remote operates on correct directory (GH#2306)",
			"FIX: Metadata merge conflicts auto-resolved on pull (GH#2466)",
			"FIX: bd list --json no longer ignored when --tree defaults to true",
			"FIX: bd doctor --fix regenerates missing metadata.json (GH#2482)",
			"FIX: bd init blocked from creating DB on wrong server (GH#2336)",
			"FIX: Worktree hooks use absolute core.hooksPath (GH#2414)",
			"FIX: BEADS_DIR stabilized from detached worktrees",
			"PERF: Close-time template subgraph loading speed improvement (GH#2458)",
			"NEW: Config-driven metadata schema enforcement",
			"NEW: --metadata for bd create, --set-metadata/--unset-metadata for bd update",
			"NEW: PreToolUse hook blocks interactive cp/mv/rm prompts",
			"NEW: Self-managing Dolt server (port collision, idle monitor, crash watchdog)",
			"NEW: bd dolt remote add/list/remove commands",
			"NEW: Auto-push to Dolt remote with 5-minute debounce",
			"NEW: Per-worktree .beads/redirect override",
			"NEW: Counter mode (issue_id_mode=counter) for sequential IDs",
			"NEW: Auto-migrate SQLite to Dolt on first bd command",
			"NEW: Label inheritance — children inherit parent labels",
			"NEW: Jira V2 API support",
			"NEW: Linear Project sync support",
			"FIX: Shadow database prevention — no more silent CREATE DATABASE",
			"FIX: Reparented child no longer appears under old parent",
			"FIX: Dolt port resolution uses ephemeral port (not hardcoded 3307)",
			"FIX: Doctor checks respect dolt-data-dir config",
			"FIX: UUID primary keys replace AUTO_INCREMENT (federation-safe)",
			"FIX: Windows compatibility (Makefile, connectex, doltserver)",
			"FIX: Batch SQL IN-clause queries prevent query explosion",
			"FIX: Conditional-blocks deps evaluated in readiness checks",
			"FIX: Migration safety — verify DB target, deduplicate, spot-check data",
			"PERF: Test parallelization — storage 3.5x, protocol 3x faster",
			"PERF: Branch-per-test isolation — doctor tests 44s → 12s",
		},
	},
	{
		Version: "0.59.0",
		Date:    "2026-03-05",
		Changes: []string{
			"NEW: bd list --tree is now the default display mode",
			"NEW: bd doctor detects fresh clone state on Dolt server",
			"NEW: bd init distinguishes server-reachable from DB-exists",
			"NEW: bd setup includes OpenCode recipe",
			"NEW: bd doctor warning suppression via config",
			"CHANGED: Daemon infrastructure fully removed — bd is purely CLI-driven",
			"CHANGED: Backup git-push defaults to OFF (explicit opt-in required)",
			"FIX: bd doctor --fix repairs broken/orphaned hook markers (GH#2344)",
			"FIX: Legacy hook migration warns on user-modified hooks",
			"FIX: Dolt push/pull uses correct database subdirectory",
			"FIX: Contributor auto-routing fallback for show/update/close (GH#2345)",
			"FIX: Init port resolution uses DefaultConfig (GH#2372)",
			"FIX: Idle monitor single-instance lock and port isolation (GH#2367)",
			"FIX: Init prevents data destruction from misleading errors (GH#2363)",
			"FIX: Circuit breaker cooldown reduced to 5s with TCP probe",
			"FIX: Deterministic ordering with ID tiebreaker in all queries",
			"FIX: Batch IN-clause queries prevent full table scans",
		},
	},
	{
		Version: "0.58.0",
		Date:    "2026-03-02",
		Changes: []string{
			"NEW: bd purge — delete closed ephemeral beads to reclaim storage",
			"NEW: bd mol last-activity — show most recent molecule activity timestamp",
			"NEW: bd show --current — show active issue without specifying ID",
			"NEW: bd doctor validate — Dolt-native conflict detection",
			"NEW: bd init --backend — explicit backend selection with SQLite deprecation",
			"NEW: --stdin flag for bd create/update (alias for --body-file -)",
			"NEW: bd preflight --check aligned with CI checks",
			"NEW: JSONL-to-Dolt migration script for pre-0.50 users",
			"NEW: bd create-form --parent for sub-issue creation with label inheritance",
			"NEW: Persistent agent memory (bd remember/memories/recall/forget)",
			"FIX: Dolt CPU spikes — batch IN-clause queries in dependencies",
			"FIX: Dolt joinIter hangs in GetReadyWork blocker computation",
			"FIX: Stealth mode (no-git-ops) now correctly prevents backup git push",
			"FIX: Stale DB connection crash in bd edit",
			"FIX: OSC escape leaks from third-party hook runners (lefthook, husky)",
			"FIX: validateIssueIDPrefix now checks allowed_prefixes (unblocks convoys)",
			"FIX: Molecule steps now appear in bd ready",
			"FIX: Cross-prefix dependency routing and validation",
			"FIX: Wisps table recreation on schema fast-path",
			"FIX: bd search avoids LIKE %% full-table scans",
			"REMOVED: SQLite backend and go-sqlite3 dependency (Dolt only)",
			"REMOVED: Deprecated commands and legacy SQLite-era scripts",
		},
	},
	{
		Version: "0.57.0",
		Date:    "2026-03-01",
		Changes: []string{
			"NEW: bd doctor --agent mode for AI agent diagnostics",
			"NEW: SSH push/pull fallback with dual-surface remote management",
			"NEW: Hook migration system — census and migration planning",
			"NEW: Section markers for git hooks (safer hook updates)",
			"NEW: bd backup init/sync/restore for Dolt-native backups",
			"NEW: bd gc, bd compact, bd flatten for standalone lifecycle",
			"NEW: Circuit breaker for Dolt server connections",
		},
	},
	{
		Version: "0.56.1",
		Date:    "2026-02-23",
		Changes: []string{
			"FIX: Release CI — remove verify-cgo hook from CGO_ENABLED=0 builds (darwin, freebsd)",
		},
	},
	{
		Version: "0.56.0",
		Date:    "2026-02-23",
		Changes: []string{
			"REMOVED: Embedded Dolt mode — server-only; binary 168MB → 41MB",
			"REMOVED: SQLite ephemeral store — wisps now in Dolt-backed table",
			"REMOVED: JSONL sync pipeline — Dolt-native push/pull only",
			"NEW: OpenTelemetry opt-in instrumentation for hooks and storage",
			"NEW: Transaction infrastructure with isolation, retry, and batch wrapping",
			"NEW: Metadata query support in bd list, bd search, bd query",
			"FIX: Atomic bond/squash/cook operations (single transaction)",
			"FIX: Double JSON encoding in daemon-mode RPC calls",
			"FIX: bd ready parent filter and blocked status propagation",
			"PERF: Test isolation from production Dolt server",
		},
	},
	{
		Version: "0.55.4",
		Date:    "2026-02-20",
		Changes: []string{
			"FIX: Release CI FreeBSD — CGO_ENABLED=0 (zig sysroot lacks stdlib.h)",
			"FIX: Release CI macOS — CGO_ENABLED=0 for darwin (zig sysroot lacks frameworks)",
			"FIX: Release CI libresolv — strip -lresolv from zig wrappers (macOS uses netgo)",
		},
	},
	{
		Version: "0.55.1",
		Date:    "2026-02-20",
		Changes: []string{
			"FIX: Release workflow YAML broken by heredoc in zig wrapper step",
			"FIX: Version consistency (marketplace.json missed in v0.55.0 bump)",
			"FIX: Go formatting and lint issues in 9 files",
		},
	},
	{
		Version: "0.55.0",
		Date:    "2026-02-20",
		Changes: []string{
			"FIX: Release CI upgraded zig 0.13→0.14 fixing AccessDenied cross-compilation bug",
			"FIX: macOS libresolv resolution with zig 0.14 (-lresolv.9 workaround)",
			"FIX: 5 pre-existing test failures and Dolt panic resolved",
			"REMOVED: ~5K lines dead code from classic sync cleanup",
		},
	},
	{
		Version: "0.54.0",
		Date:    "2026-02-18",
		Changes: []string{
			"FIX: mol squash auto-closes wisp root to prevent Dolt lock errors",
			"FIX: Release CI zig cross-compilation cache race (--parallelism 1)",
			"FIX: Android ARM64 build uses CGO_ENABLED=0 (server mode only)",
			"NEW: Mux setup recipe with layered AGENTS and managed hooks",
			"CHORE: Remove daemon references from doctor system for post-daemon architecture",
			"CHORE: Remove ~5K lines of dead code from classic cleanup",
			"FIX: Upgrade zig 0.13.0 to 0.14.0 to fix AccessDenied bug in cross-compilation",
		},
	},
	{
		Version: "0.53.0",
		Date:    "2026-02-18",
		Changes: []string{
			"NEW: Dolt-in-Git sync — native Dolt push/pull via git remotes replaces JSONL pipeline",
			"NEW: bd dolt start/stop — explicit Dolt server management (#1813)",
			"NEW: bd dolt commit — desire-path ergonomics for Dolt data",
			"NEW: Server mode without CGO — OpenFromConfig exported (#1805)",
			"NEW: Hosted Dolt support — TLS, auth, explicit branch config",
			"NEW: bd mol wisp gc --closed for bulk purge of closed wisps",
			"NEW: Storage interface decouples from concrete DoltStore",
			"NEW: Lock health diagnostics in bd doctor",
			"FIX: Pre-commit deadlock on embedded Dolt (#1841)",
			"FIX: bd doctor --fix hang — run fixes in-process (#1850)",
			"FIX: Dolt lock errors surfaced with guidance (#1816)",
			"FIX: BEADS_DIR config loading (#1854)",
			"REMOVED: JSONL sync-branch pipeline (~11,000 lines deleted)",
			"REMOVED: Daemon infrastructure, 3-way merge remnants, dead stubs",
		},
	},
	{
		Version: "0.52.0",
		Date:    "2026-02-16",
		Changes: []string{
			"NEW: bd ready --include-ephemeral flag to include ephemeral issues in ready work",
			"FIX: Doctor redirect target resolution (#1803)",
			"FIX: Guard dolt directory creation with server-mode check (#1800)",
			"FIX: Tilde expansion in core.hooksPath on Windows (#1798)",
			"FIX: Worktree redirect path resolution from worktree root (#1791)",
			"FIX: Block rename-prefix in git worktrees (#1792)",
			"REMOVED: Dead git-portable sync functions (#1793)",
		},
	},
	{
		Version: "0.51.0",
		Date:    "2026-02-16",
		Changes: []string{
			"REMOVED: Dolt-native cleanup — removed SQLite backend, JSONL sync, 3-way merge, tombstones, storage factory, daemon stubs (8-phase refactor)",
			"CHANGED: bd sync is now a no-op — Dolt handles persistence directly",
			"FIX: Dolt config test corruption in worktree environments (t.Setenv fix)",
			"FIX: Batch DeleteIssues hang on large ID sets with correctness hardening",
			"FIX: bd mol current step readiness uses analyzeMoleculeParallel",
			"FIX: bd doctor AccessLock integration, --yes for repo fingerprint",
			"FIX: GetReadyWork excludes workflow/identity types",
			"PERF: CASCADE deletes cut deletion queries by 60%",
			"PERF: Schema init skip when already at current version",
			"DOCS: 10+ docs updated from SQLite to Dolt, deprecated docs removed",
		},
	},
	{
		Version: "0.50.3",
		Date:    "2026-02-15",
		Changes: []string{
			"REFACTOR: All tracker CLIs (Linear, GitLab, Jira) now use shared SyncEngine — eliminates ~800 lines of duplicated sync code",
			"NEW: SyncEngine PullHooks/PushHooks for tracker-specific behaviors (GenerateID, FormatDescription, ContentEqual, etc.)",
			"NEW: Jira native integration in internal/jira/ with REST API v3, ADF conversion, field mapping",
			"NEW: Tracker plugin registry with auto-discovery (tracker.Register + init())",
			"FIX: Jira State mapping bug — stale pointer assignment could cause incorrect status mapping",
			"FIX: CI Windows build — test helper file renamed to _test.go suffix",
			"PERF: Test suite — cached git template replaces ~60 subprocess calls",
		},
	},
	{
		Version: "0.50.1",
		Date:    "2026-02-14",
		Changes: []string{
			"CHANGED: Default backend is now Dolt for new bd init projects (existing SQLite projects unaffected)",
			"NEW: bd graph terminal-native DAG visualization, DOT export, interactive HTML export",
			"NEW: bd sql command for raw SQL access (table, JSON, CSV output)",
			"NEW: bd help --all for complete command reference dump",
			"NEW: decision built-in issue type",
			"NEW: Cross-database dependency resolution via prefix routes in bd show/graph/blocked",
			"NEW: bd doctor artifact cleanup (--check=artifacts --clean) and Dolt corruption recovery (--fix)",
			"NEW: bd doctor Claude Code integration checks and grouped category output",
			"REMOVED: Daemon/RPC subsystem and JSONL sync layer fully removed",
			"FIX: bd close enforces gate satisfaction (--force to bypass)",
			"FIX: bd show exits non-zero when issue not found",
			"FIX: Dolt joinIter panic prevented (replaced IN/EXISTS subqueries with Go-level filtering)",
			"FIX: Embedded Dolt self-deadlock in git hooks and bd migrate",
			"FIX: bd ready excludes children of deferred parents",
		},
	},
	{
		Version: "0.49.6",
		Date:    "2026-02-09",
		Changes: []string{
			"REVERT: Embedded Dolt mode restored (removal was only intended for Gas Town, not Beads)",
			"REMOVED: Daemon subsystem fully removed from bd CLI (Dolt replaces daemon-based sync)",
			"REMOVED: JSONL flush/sync machinery deleted (-7,634 lines); JSONL functions are now no-ops",
			"CLEANUP: Removed 171 dead daemonClient branches and 46 markDirtyAndScheduleFlush no-op calls",
		},
	},
	{
		Version: "0.49.5",
		Date:    "2026-02-08",
		Changes: []string{
			"NEW: bd search --has/--no flags for content and null-check filtering",
			"NEW: bd promote command for wisp-to-bead promotion",
			"NEW: bd todo command for lightweight task management",
			"NEW: bd find-duplicates for AI-powered duplicate detection",
			"NEW: bd validate integrated into bd doctor --check=validate",
			"NEW: Dolt fail-fast TCP check before MySQL protocol init",
			"SECURITY: SQL identifier validation prevents injection in dynamic table/db names",
			"SECURITY: Path traversal fix in export handler; command injection fix in import",
			"FIX: RPC mutation events now include issueID (was zero-value for label/dep ops)",
			"FIX: Daemon YAML config recognizes both hyphen and underscore variants",
			"FIX: Doctor role check falls back to database config",
			"FIX: SQLite Close() idempotent (WAL retry deadlock fix)",
			"FIX: SQLITE_BUSY retry for all BEGIN IMMEDIATE calls",
			"FIX: Dolt cross-rig contamination prevented with prefix-based db names",
			"FIX: bd list separates parent-child from blocks display",
			"FIX: Cross-prefix ID resolution in multi-repo scenarios",
			"CHANGE: Embedded Dolt mode fully removed (server-only connections)",
			"CHANGE: bd init defaults to chaining hooks (no prompt)",
			"CHANGE: brew upgrade command corrected to 'brew upgrade beads'",
		},
	},
	{
		Version: "0.49.4",
		Date:    "2026-02-05",
		Changes: []string{
			"NEW: --label-pattern and --label-regex flags for bd list and bd ready - glob and regex filtering on labels",
			"NEW: Simple query language for complex bd list filtering",
			"NEW: spec_id field for linking issues to specification documents",
			"NEW: Wisp type field for TTL-based compaction of ephemeral molecules",
			"NEW: Dolt schema migration runner and doctor validation checks",
			"NEW: --metadata flag for bd update (JSON metadata from CLI)",
			"NEW: config.local.yaml for local configuration overrides",
			"FIX: JSONL file locking prevents race conditions in concurrent writes",
			"FIX: Merge driver preserves all issue fields (spec_id, metadata, deps)",
			"FIX: Atomic bd claim with compare-and-swap semantics",
			"FIX: Dolt lock contention - advisory flock prevents zombie processes",
			"FIX: Windows Dolt build via pure-Go regex backend",
			"CHANGE: bd ready excludes in_progress issues (shows only claimable work)",
		},
	},
	{
		Version: "0.49.3",
		Date:    "2026-01-31",
		Changes: []string{
			"FIX: Dolt split-brain eliminated - DatabasePath() always resolves to .beads/dolt/ for dolt backend; JSONL auto-import blocked in dolt-native mode",
			"CHANGE: Embedded Dolt is now the default - server mode is opt-in via dolt_mode: server",
			"FIX: Dolt mergeJoinIter panic on type-filtered queries eliminated",
			"FIX: CGO/ICU build - Makefile and test.sh auto-detect Homebrew icu4c paths on macOS",
		},
	},
	{
		Version: "0.49.2",
		Date:    "2026-01-31",
		Changes: []string{
			"NEW: GitLab backend - Bidirectional issue sync with GitLab (bd gitlab sync/status/projects)",
			"NEW: Key-value store - bd kv get/set/delete/list for persistent key-value storage",
			"NEW: Per-issue JSON metadata field for custom structured data (SQLite + Dolt)",
			"NEW: Events JSONL export - Opt-in audit trail via events-export config",
			"NEW: Role configuration - Explicit roles via git, interactive contributor prompt",
			"NEW: bd backend and bd sync mode subcommands for storage inspection",
			"NEW: Dolt auto-detect server mode during bd init",
			"NEW: comment_count in JSON views, comment timestamps with --local-time",
			"CHANGE: Removed Gas Town-specific code from beads core (hooks, validation, role types)",
			"CHANGE: Storage layer refactored for backend-agnostic access",
			"FIX: Worktree support - GIT_DIR/GIT_WORK_TREE in sync operations",
			"FIX: Graceful Dolt server-to-embedded fallback",
			"FIX: Multiple sync fixes for dolt-native mode and sync-branch",
			"FIX: Formula handlebars, ephemeral sync exclusion, daemon idempotency",
		},
	},
	{
		Version: "0.49.1",
		Date:    "2026-01-25",
		Changes: []string{
			"NEW: Dolt backend fully supported - Extensively tested and ready for community evaluation",
			"NOTE: Dolt is not enabled by default - We encourage users to try it and report feedback!",
			"NEW: bd activity --details/-d - Full issue information in activity feed (#1317)",
			"NEW: bd export --id/--parent - Targeted exports with filters (#1292)",
			"NEW: bd update --append-notes - Append to existing notes (#1304)",
			"NEW: bd show --id - For IDs that look like flags",
			"NEW: bd doctor --server - Dolt server mode health checks",
			"NEW: Dolt server mode - Multi-client access for shared Dolt databases",
			"NEW: Dolt auto-commit on writes with explicit commit authors (#1267)",
			"FIX: Daemon stack overflow on empty database path (#1288, #1313)",
			"FIX: bd list --json optimization - Fetch only needed dependencies (#1316)",
			"FIX: Import custom issue types (#1322)",
			"FIX: SQLite transaction improvements (#1272, #1276)",
			"FIX: Multiple Dolt backend fixes for hooks, routing, and daemon compatibility",
			"DOCS: Comprehensive Dolt backend guide, now at docs/architecture/dolt.md (#1310)",
		},
	},
	{
		Version: "0.49.0",
		Date:    "2026-01-21",
		Changes: []string{
			"NEW: Dolt federation - Peer-to-peer issue sync with bd federation sync command",
			"NEW: SQLite to Dolt migration - bd migrate dolt converts existing repos",
			"NEW: bd children <id> - Display child issues for a parent",
			"NEW: bd rename <old> <new> - Rename issue IDs",
			"NEW: bd view - Alias for bd show command",
			"NEW: bd config validate - Validate sync configuration",
			"NEW: Jujutsu (jj) VCS support - Beads now works with jj repositories",
			"NEW: Per-field merge strategies for conflict resolution",
			"NEW: -m flag as alias for --description in bd create",
			"CHANGED: Auto-routing disabled by default - Enable with routing.mode: auto (#1177)",
			"CHANGED: Gas Town types removed from core - Use types.custom configuration",
			"FIX: Daemon zombie state after DB replacement (#1213)",
			"FIX: WSL2 Docker Desktop - Detect bind mounts and disable WAL mode (#1224)",
			"FIX: Daemon stack overflow in handleStaleLock (#1238)",
			"FIX: Molecule steps excluded from bd ready (#1246)",
			"FIX: Tree ordering stabilization for consistent --tree output (#1228)",
		},
	},
	{
		Version: "0.48.0",
		Date:    "2026-01-17",
		Changes: []string{
			"NEW: VersionedStorage interface - Abstract storage layer with history/diff/branch operations",
			"NEW: bd types command - List valid issue types with descriptions",
			"NEW: bd close -m flag - Alias for --reason (git commit convention)",
			"NEW: RepoContext API - Centralized git operations context",
			"WIP: Dolt backend improvements - Bootstrap from JSONL, hook infrastructure, bd compact --dolt",
			"FIX: Doctor sync branch check - Removed destructive --fix behavior (GH#1062)",
			"FIX: Duplicate merge target - Use combined weight for better selection (GH#1022)",
			"FIX: Worktree exclude paths - Correct --git-common-dir usage (GH#1053)",
			"FIX: Daemon git.author - Apply configured author to sync commits",
			"FIX: Windows CGO-free builds - Enable building without CGO (#1117)",
			"FIX: Git hooks in worktrees - Fix hook execution in linked worktrees (#1126)",
		},
	},
}
