package setup

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/jonbaldie/beads/internal/templates/agents"
)

const (
	codexInstructionMarker         = "BEADS CODEX SETUP"
	codexBeginMarker               = "<!-- BEGIN " + codexInstructionMarker + ": generated by bd setup codex -->"
	codexEndMarker                 = "<!-- END " + codexInstructionMarker + " -->"
	codexInstructionsFile          = "AGENTS.md"
	codexConfigDir                 = ".codex"
	codexConfigFile                = "config.toml"
	codexHooksFile                 = "hooks.json"
	codexHomeEnvVar                = "CODEX_HOME"
	codexLegacySessionStartCommand = `bd prime --stealth | jq -Rs '{hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:.}}'`
)

var (
	codexEnvProvider             = defaultCodexEnv
	errCodexInstructionsMissing  = errors.New("codex instructions not installed")
	errCodexInstructionsStale    = errors.New("codex instructions are stale")
	errCodexInstructionsNoMarker = errors.New("codex instructions section missing")
	errCodexHooksMissing         = errors.New("codex hooks not installed")
	errCodexHooksStale           = errors.New("codex hooks are stale")
	errCodexFeatureMissing       = errors.New("codex hooks feature flag not enabled")
)

type codexEnv struct {
	stdout     io.Writer
	stderr     io.Writer
	homeDir    string
	projectDir string
	ensureDir  func(string, os.FileMode) error
	readFile   func(string) ([]byte, error)
	writeFile  func(string, []byte) error
	removeFile func(string) error
	getenv     func(string) string
}

func defaultCodexEnv() (codexEnv, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return codexEnv{}, fmt.Errorf("home directory: %w", err)
	}
	workDir, err := os.Getwd()
	if err != nil {
		return codexEnv{}, fmt.Errorf("working directory: %w", err)
	}
	return codexEnv{
		stdout:     os.Stdout,
		stderr:     os.Stderr,
		homeDir:    home,
		projectDir: workDir,
		ensureDir:  EnsureDir,
		readFile:   os.ReadFile,
		writeFile: func(path string, data []byte) error {
			return atomicWriteFile(path, data)
		},
		removeFile: os.Remove,
		getenv:     os.Getenv,
	}, nil
}

func InstallCodex(global bool) error {
	env, err := codexEnvProvider()
	if err != nil {
		return HandleError("%v", err)
	}
	return installCodex(env, global)
}

// InstallCodexProject installs project-local Codex integration, returning an
// error instead of exiting. Used by bd init to integrate Codex setup
// automatically.
func InstallCodexProject() error {
	env, err := codexEnvProvider()
	if err != nil {
		return err
	}
	return installCodex(env, false)
}

func installCodex(env codexEnv, global bool) error {
	if err := installAgentSkill(codexAgentSkillEnv(env, global)); err != nil {
		return err
	}
	if err := installCodexNativeHooks(env, global); err != nil {
		return err
	}
	return installCodexInstructions(env, global)
}

func CheckCodex(global bool) error {
	env, err := codexEnvProvider()
	if err != nil {
		return HandleError("%v", err)
	}
	return checkCodex(env, global)
}

func checkCodex(env codexEnv, global bool) error {
	if err := checkAgentSkill(codexAgentSkillEnv(env, global), codexSetupCommand(global)); err != nil {
		return err
	}
	if err := checkCodexNativeHooks(env, global); err != nil {
		return err
	}
	return checkCodexInstructions(env, global)
}

func RemoveCodex(global bool) error {
	env, err := codexEnvProvider()
	if err != nil {
		return HandleError("%v", err)
	}
	return removeCodex(env, global)
}

func removeCodex(env codexEnv, global bool) error {
	// The agent skill is shared with Cursor (same .agents/skills/beads path).
	// Only remove it if Cursor isn't still relying on it.
	if cursorIntegrationInstalledAt(env.readFile, codexRootDir(env, global), global) {
		_, _ = fmt.Fprintln(env.stdout, "Keeping Beads agent skill (still used by Cursor integration)")
	} else if err := removeAgentSkill(codexAgentSkillEnv(env, global)); err != nil {
		return err
	}
	if err := removeCodexNativeHooks(env, global); err != nil {
		return err
	}
	return removeCodexInstructions(env, global)
}

// cursorIntegrationInstalledAt reports whether Cursor's bd integration exists
// under root (projectDir for project scope, homeDir for global scope), using the
// provided readFile so the check stays hermetic in tests. Both Cursor and Codex
// install the shared .agents/skills/beads skill, so removing one must not delete
// the skill while the other still relies on it.
func cursorIntegrationInstalledAt(readFile func(string) ([]byte, error), root string, global bool) bool {
	if data, err := readFile(filepath.Join(root, ".cursor", "hooks.json")); err == nil {
		if config, perr := parseHooksJSON(data); perr == nil && cursorBeadsHooksPresent(config) {
			return true
		}
	}
	if !global {
		if _, err := readFile(filepath.Join(root, cursorRulesPath)); err == nil {
			return true
		}
	}
	return false
}

func codexSetupCommand(global bool) string {
	if global {
		return "bd setup codex --global"
	}
	return "bd setup codex"
}

func codexRootDir(env codexEnv, global bool) string {
	if global {
		return env.homeDir
	}
	return env.projectDir
}

func codexHomeDir(env codexEnv) string {
	if env.getenv != nil {
		if path := env.getenv(codexHomeEnvVar); path != "" {
			return path
		}
	}
	return filepath.Join(env.homeDir, codexConfigDir)
}

func codexInstructionsPath(env codexEnv, global bool) string {
	if global {
		return filepath.Join(codexHomeDir(env), codexInstructionsFile)
	}
	return filepath.Join(env.projectDir, codexInstructionsFile)
}

func codexConfigRoot(env codexEnv, global bool) string {
	if global {
		return codexHomeDir(env)
	}
	return filepath.Join(env.projectDir, codexConfigDir)
}

func codexConfigPath(env codexEnv, global bool) string {
	return filepath.Join(codexConfigRoot(env, global), codexConfigFile)
}

func codexHooksPath(env codexEnv, global bool) string {
	return filepath.Join(codexConfigRoot(env, global), codexHooksFile)
}

func codexAgentSkillEnv(env codexEnv, global bool) agentSkillEnv {
	return agentSkillEnv{
		stdout:     env.stdout,
		stderr:     env.stderr,
		projectDir: codexRootDir(env, global),
		ensureDir:  env.ensureDir,
		readFile:   env.readFile,
		writeFile:  env.writeFile,
		removeFile: env.removeFile,
	}
}

func codexManagedSection() string {
	return codexBeginMarker + "\n" + agents.CodexSectionBody() + "\n" + codexEndMarker
}

func installCodexInstructions(env codexEnv, global bool) error {
	path := codexInstructionsPath(env, global)
	if global {
		_, _ = fmt.Fprintln(env.stdout, "Installing Codex instructions globally...")
	} else {
		_, _ = fmt.Fprintln(env.stdout, "Installing Codex instructions for this project...")
	}

	if err := env.ensureDir(filepath.Dir(path), 0o755); err != nil {
		_, _ = fmt.Fprintf(env.stderr, "Error: %v\n", err)
		return err
	}

	var current string
	data, err := env.readFile(path)
	switch {
	case err == nil:
		current = string(data)
	case os.IsNotExist(err):
	default:
		_, _ = fmt.Fprintf(env.stderr, "Error: read %s: %v\n", path, err)
		return err
	}

	next := upsertCodexManagedSection(current)
	if err := env.writeFile(path, []byte(next)); err != nil {
		_, _ = fmt.Fprintf(env.stderr, "Error: write %s: %v\n", path, err)
		return err
	}

	_, _ = fmt.Fprintln(env.stdout, "✓ Codex instructions installed")
	_, _ = fmt.Fprintf(env.stdout, "  File: %s\n", path)
	_, _ = fmt.Fprintln(env.stdout, "Restart Codex if it is already running.")
	return nil
}

func checkCodexInstructions(env codexEnv, global bool) error {
	path := codexInstructionsPath(env, global)
	data, err := env.readFile(path)
	if os.IsNotExist(err) {
		_, _ = fmt.Fprintf(env.stdout, "✗ Codex instructions not found: %s\n", path)
		_, _ = fmt.Fprintf(env.stdout, "  Run: %s\n", codexSetupCommand(global))
		return errCodexInstructionsMissing
	}
	if err != nil {
		_, _ = fmt.Fprintf(env.stderr, "Error: read %s: %v\n", path, err)
		return err
	}

	section, ok := extractCodexManagedSection(string(data))
	if !ok {
		_, _ = fmt.Fprintf(env.stdout, "⚠ Codex instructions exist but no beads section found: %s\n", path)
		_, _ = fmt.Fprintf(env.stdout, "  Run: %s\n", codexSetupCommand(global))
		return errCodexInstructionsNoMarker
	}
	if section != codexManagedSection() {
		_, _ = fmt.Fprintf(env.stdout, "⚠ Codex instructions installed but stale: %s\n", path)
		_, _ = fmt.Fprintf(env.stdout, "  Run: %s\n", codexSetupCommand(global))
		return errCodexInstructionsStale
	}

	_, _ = fmt.Fprintf(env.stdout, "✓ Codex instructions installed: %s\n", path)
	return nil
}

func removeCodexInstructions(env codexEnv, global bool) error {
	path := codexInstructionsPath(env, global)
	_, _ = fmt.Fprintln(env.stdout, "Removing Codex instructions...")
	data, err := env.readFile(path)
	if os.IsNotExist(err) {
		_, _ = fmt.Fprintln(env.stdout, "No Codex instructions file found")
		return nil
	}
	if err != nil {
		_, _ = fmt.Fprintf(env.stderr, "Error: read %s: %v\n", path, err)
		return err
	}

	next, ok := removeCodexManagedSection(string(data))
	if !ok {
		_, _ = fmt.Fprintln(env.stdout, "No beads Codex section found")
		return nil
	}
	if err := env.writeFile(path, []byte(next)); err != nil {
		_, _ = fmt.Fprintf(env.stderr, "Error: write %s: %v\n", path, err)
		return err
	}

	_, _ = fmt.Fprintln(env.stdout, "✓ Codex instructions removed")
	return nil
}

func upsertCodexManagedSection(content string) string {
	section := codexManagedSection()
	if _, ok := extractCodexManagedSection(content); ok {
		start := strings.Index(content, codexBeginMarker)
		end := strings.Index(content, codexEndMarker)
		end += len(codexEndMarker)
		return content[:start] + section + content[end:]
	}
	if strings.TrimSpace(content) == "" {
		return "# Codex Instructions\n\n" + section + "\n"
	}
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return content + "\n" + section + "\n"
}

func extractCodexManagedSection(content string) (string, bool) {
	start := strings.Index(content, codexBeginMarker)
	end := strings.Index(content, codexEndMarker)
	if start == -1 || end == -1 || start > end {
		return "", false
	}
	end += len(codexEndMarker)
	return content[start:end], true
}

func removeCodexManagedSection(content string) (string, bool) {
	start := strings.Index(content, codexBeginMarker)
	end := strings.Index(content, codexEndMarker)
	if start == -1 || end == -1 || start > end {
		return content, false
	}
	end += len(codexEndMarker)
	if end < len(content) && content[end] == '\n' {
		end++
	}
	return content[:start] + content[end:], true
}
